# Generated by Django 5.0.4 on 2024-05-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_remove_booking_tour_remove_tour_price_adult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(null=True, upload_to='image/ticket'),
        ),
    ]
