# Generated by Django 5.0.4 on 2024-05-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_like_active_like_alter_rating_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='active_like',
            new_name='liked',
        ),
        migrations.AddField(
            model_name='ticket',
            name='departure_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
